# Generated by Django 6.0.2 on 2026-07-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Dokumen')),
                ('pdf_url', models.URLField(default='', max_length=500, verbose_name='URL PDF')),
                ('filename', models.CharField(blank=True, help_text='Original filename, e.g. voli.pdf', max_length=255, verbose_name='Nama File')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Teks Hasil Ekstraksi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Unggah')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Dokumen Chat AI',
                'verbose_name_plural': 'Dokumen Chat AI',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_history', models.JSONField(blank=True, default=list, verbose_name='Riwayat Chat')),
                ('token_usage', models.PositiveIntegerField(default=0, verbose_name='Penggunaan Token')),
                ('token_cap', models.PositiveIntegerField(default=10000, verbose_name='Batas Token')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Sesi Chat',
                'verbose_name_plural': 'Sesi Chat',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('gender', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10, verbose_name='Jenis Kelamin')),
                ('kelas', models.CharField(blank=True, max_length=5, verbose_name='Kelas')),
                ('nisn', models.CharField(blank=True, max_length=20, verbose_name='NISN')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir')),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Berat Badan (kg)')),
                ('tinggi_badan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tinggi Badan (cm)')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Role / Peran')),
                ('subkategori', models.CharField(blank=True, max_length=255, verbose_name='Subkategori')),
                ('is_kapten', models.BooleanField(default=False, verbose_name='Apakah Kapten?')),
                ('dynamic_data', models.JSONField(blank=True, default=dict, verbose_name='Data Dinamis Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Daftar Anggota',
                'ordering': ['-is_kapten', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Kunci')),
                ('value', models.TextField(blank=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'Info Tambahan Tim',
                'verbose_name_plural': 'Info Tambahan Tim',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tim', models.CharField(max_length=150, verbose_name='Nama Tim')),
                ('school', models.CharField(max_length=200, verbose_name='Asal Sekolah')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('competition', models.CharField(max_length=100, verbose_name='Cabang Olahraga (Slug)')),
                ('jenjang', models.CharField(choices=[('SMP', 'SMP'), ('SMA', 'SMA')], max_length=3, verbose_name='Jenjang')),
                ('regis_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('PENDINGTF', 'Pending Transfer'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status Pendaftaran')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Nama Bank')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Nomor Rekening')),
                ('account_holder', models.CharField(blank=True, max_length=150, verbose_name='Nama Pemilik Rekening')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tim',
                'verbose_name_plural': 'Daftar Tim',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pembayaran', 'Bukti Pembayaran'), ('kartuPelajar', 'Kartu Pelajar Kapten'), ('selfie', 'Selfie Dengan Kartu Pelajar'), ('suratPernyataan', 'Surat Pernyataan Tim'), ('suratIzin', 'Surat Izin Sekolah')], max_length=30, verbose_name='Jenis Berkas')),
                ('file', models.FileField(upload_to='Registration/team_files/', verbose_name='Berkas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Unggah')),
            ],
            options={
                'verbose_name': 'Berkas Tim',
                'verbose_name_plural': 'Berkas Tim',
                'ordering': ['file_type'],
            },
        ),
        migrations.CreateModel(
            name='MemberFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50, verbose_name='Jenis Berkas')),
                ('file', models.FileField(upload_to='Registration/member_files/', verbose_name='Berkas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Unggah')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='regis.member', verbose_name='Anggota')),
            ],
            options={
                'verbose_name': 'Berkas Anggota',
                'verbose_name_plural': 'Berkas Anggota',
                'ordering': ['file_type'],
            },
        ),
    ]
