# Generated by Django 6.0.2 on 2026-06-11 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tim', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('competition', models.CharField(max_length=100)),
                ('jenjang', models.CharField(choices=[('SMP', 'SMP'), ('SMA', 'SMA')], max_length=3)),
                ('regis_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('PENDINGTF', 'Pending Transfer'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_holder', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('kelas', models.CharField(blank=True, max_length=5)),
                ('nisn', models.CharField(blank=True, max_length=20)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('tinggi_badan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('subkategori', models.CharField(blank=True, max_length=255)),
                ('is_kapten', models.BooleanField(default=False)),
                ('dynamic_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='regis.team')),
            ],
            options={
                'ordering': ['-is_kapten', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='regis/member_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='regis.member')),
            ],
            options={
                'ordering': ['file_type'],
                'unique_together': {('member', 'file_type')},
            },
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='regis.team')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('team', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TeamFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pembayaran', 'Bukti Pembayaran'), ('kartuPelajar', 'Kartu Pelajar Kapten'), ('selfie', 'Selfie Dengan Kartu Pelajar'), ('suratPernyataan', 'Surat Pernyataan Tim'), ('suratIzin', 'Surat Izin Sekolah')], max_length=30)),
                ('file', models.FileField(upload_to='regis/team_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='regis.team')),
            ],
            options={
                'ordering': ['file_type'],
                'unique_together': {('team', 'file_type')},
            },
        ),
    ]
