# Generated by Django 6.0.2 on 2026-06-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-is_kapten', 'created_at'], 'verbose_name': 'Anggota', 'verbose_name_plural': 'Daftar Anggota'},
        ),
        migrations.AlterModelOptions(
            name='memberfile',
            options={'ordering': ['file_type'], 'verbose_name': 'Berkas Anggota', 'verbose_name_plural': 'Berkas Anggota'},
        ),
        migrations.AlterModelOptions(
            name='otherinfo',
            options={'ordering': ['key'], 'verbose_name': 'Info Tambahan Tim', 'verbose_name_plural': 'Info Tambahan Tim'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tim', 'verbose_name_plural': 'Daftar Tim'},
        ),
        migrations.AlterModelOptions(
            name='teamfile',
            options={'ordering': ['file_type'], 'verbose_name': 'Berkas Tim', 'verbose_name_plural': 'Berkas Tim'},
        ),
        migrations.AlterField(
            model_name='member',
            name='berat_badan',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Berat Badan (kg)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dynamic_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data Dinamis Tambahan'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_kapten',
            field=models.BooleanField(default=False, verbose_name='Apakah Kapten?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='kelas',
            field=models.CharField(blank=True, max_length=5, verbose_name='Kelas'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nama',
            field=models.CharField(max_length=200, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nisn',
            field=models.CharField(blank=True, max_length=20, verbose_name='NISN'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nomor_telepon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Role / Peran'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subkategori',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subkategori'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='regis.team', verbose_name='Tim'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tinggi_badan',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Tinggi Badan (cm)'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='file',
            field=models.FileField(upload_to='regis/member_files/', verbose_name='Berkas'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='file_type',
            field=models.CharField(max_length=50, verbose_name='Jenis Berkas'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='regis.member', verbose_name='Anggota'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Unggah'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Kunci'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='regis.team', verbose_name='Tim'),
        ),
        migrations.AlterField(
            model_name='otherinfo',
            name='value',
            field=models.TextField(blank=True, verbose_name='Nilai'),
        ),
        migrations.AlterField(
            model_name='team',
            name='account_holder',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Pemilik Rekening'),
        ),
        migrations.AlterField(
            model_name='team',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nomor Rekening'),
        ),
        migrations.AlterField(
            model_name='team',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Bank'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='Kapten Tim (User)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='competition',
            field=models.CharField(max_length=100, verbose_name='Cabang Olahraga (Slug)'),
        ),
        migrations.AlterField(
            model_name='team',
            name='jenjang',
            field=models.CharField(choices=[('SMP', 'SMP'), ('SMA', 'SMA')], max_length=3, verbose_name='Jenjang'),
        ),
        migrations.AlterField(
            model_name='team',
            name='nama_tim',
            field=models.CharField(max_length=150, verbose_name='Nama Tim'),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='regis_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('PENDINGTF', 'Pending Transfer'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status Pendaftaran'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school',
            field=models.CharField(max_length=200, verbose_name='Asal Sekolah'),
        ),
        migrations.AlterField(
            model_name='teamfile',
            name='file',
            field=models.FileField(upload_to='regis/team_files/', verbose_name='Berkas'),
        ),
        migrations.AlterField(
            model_name='teamfile',
            name='file_type',
            field=models.CharField(choices=[('pembayaran', 'Bukti Pembayaran'), ('kartuPelajar', 'Kartu Pelajar Kapten'), ('selfie', 'Selfie Dengan Kartu Pelajar'), ('suratPernyataan', 'Surat Pernyataan Tim'), ('suratIzin', 'Surat Izin Sekolah')], max_length=30, verbose_name='Jenis Berkas'),
        ),
        migrations.AlterField(
            model_name='teamfile',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='regis.team', verbose_name='Tim'),
        ),
        migrations.AlterField(
            model_name='teamfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Unggah'),
        ),
    ]
