# Generated by Django 6.0.2 on 2026-07-21 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='Kapten Tim (User)'),
        ),
        migrations.AddField(
            model_name='otherinfo',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='regis.team', verbose_name='Tim'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='regis.team', verbose_name='Tim'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='regis.team', verbose_name='Tim'),
        ),
        migrations.AddField(
            model_name='teamfile',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='regis.team', verbose_name='Tim'),
        ),
        migrations.AlterUniqueTogether(
            name='memberfile',
            unique_together={('member', 'file_type')},
        ),
        migrations.AlterUniqueTogether(
            name='otherinfo',
            unique_together={('team', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='teamfile',
            unique_together={('team', 'file_type')},
        ),
    ]
