# Generated by Django 6.0.2 on 2026-06-15 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_alter_member_options_alter_memberfile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Dokumen')),
                ('file', models.FileField(upload_to='regis/chat_documents/', verbose_name='Berkas PDF')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Teks Hasil Ekstraksi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Unggah')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Dokumen Chat AI',
                'verbose_name_plural': 'Dokumen Chat AI',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_history', models.JSONField(blank=True, default=list, verbose_name='Riwayat Chat')),
                ('token_usage', models.PositiveIntegerField(default=0, verbose_name='Penggunaan Token')),
                ('token_cap', models.PositiveIntegerField(default=10000, verbose_name='Batas Token')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='regis.team', verbose_name='Tim')),
            ],
            options={
                'verbose_name': 'Sesi Chat',
                'verbose_name_plural': 'Sesi Chat',
            },
        ),
    ]
