# Generated by Django 6.0.2 on 2026-08-03 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['created_at'], 'verbose_name': 'Anggota', 'verbose_name_plural': 'Daftar Anggota'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_kapten',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Akun Perwakilan Tim'),
        ),
    ]
