# Generated by Django 6.0.2 on 2026-08-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0003_alter_member_options_remove_member_is_kapten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfile',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, verbose_name='Format Berkas'),
        ),
        migrations.AddField(
            model_name='memberfile',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL Berkas'),
        ),
        migrations.AddField(
            model_name='memberfile',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cloudinary Public ID'),
        ),
        migrations.AddField(
            model_name='teamfile',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, verbose_name='Format Berkas'),
        ),
        migrations.AddField(
            model_name='teamfile',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL Berkas'),
        ),
        migrations.AddField(
            model_name='teamfile',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cloudinary Public ID'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Registration/member_files/', verbose_name='Berkas (lama)'),
        ),
        migrations.AlterField(
            model_name='teamfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Registration/team_files/', verbose_name='Berkas (lama)'),
        ),
    ]
