# Generated by Django 6.0.2 on 2026-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0003_chatdocument_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='chatdocument',
            name='filename',
            field=models.CharField(blank=True, help_text='Original filename, e.g. voli.pdf', max_length=255, verbose_name='Nama File'),
        ),
        migrations.AddField(
            model_name='chatdocument',
            name='pdf_url',
            field=models.URLField(default='', max_length=500, verbose_name='URL PDF'),
        ),
        migrations.AlterField(
            model_name='memberfile',
            name='file',
            field=models.FileField(upload_to='Registration/member_files/', verbose_name='Berkas'),
        ),
        migrations.AlterField(
            model_name='teamfile',
            name='file',
            field=models.FileField(upload_to='Registration/team_files/', verbose_name='Berkas'),
        ),
    ]
