# Generated by Django 6.0.2 on 2026-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0004_memberfile_file_format_memberfile_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamfile',
            name='file',
        ),
        migrations.AlterField(
            model_name='teamfile',
            name='file_url',
            field=models.URLField(max_length=500, verbose_name='URL Berkas'),
        ),
    ]
