from rest_framework import serializers
from django.contrib.auth import get_user_model
from django.utils import timezone
from .models import Transaction

User = get_user_model()

class UserBalanceSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['email', 'nis', 'first_name', 'current_saldo', 'division_name', 'role']


class TransactionSerializer(serializers.ModelSerializer):
    merchant_stand_name = serializers.CharField(source='merchant_stand.name', read_only=True)
    
    # 🌟 FIX 1: Treat sender/receiver as plain strings instead of model relations
    sender = serializers.CharField(read_only=True, allow_null=True)
    receiver = serializers.CharField(read_only=True, allow_null=True)
    
    # 🌟 FIX 2: Since we cannot dot-walk relations anymore, use SerializerMethodFields
    # to dynamically look up the name from the User table if needed.
    sender_name = serializers.SerializerMethodField()
    receiver_name = serializers.SerializerMethodField()
    
    formatted_time = serializers.SerializerMethodField()
    formatted_date = serializers.SerializerMethodField()

    class Meta:
        model = Transaction
        fields = [
            'id', 'amount', 'type', 'timestamp', 'formatted_time', 'formatted_date',
            'description', 'sender', 'sender_name', 'receiver', 'receiver_name',
            'merchant_stand', 'merchant_stand_name', 'reference_id'
        ]

    # Dynamically find the person's name using the stored string identifier
    def get_sender_name(self, obj):
        if not obj.sender:
            return "System"
        # Assuming you stored the user's email or NIS inside the CharField:
        user = User.objects.filter(email=obj.sender).first() or User.objects.filter(nis=obj.sender).first()
        return user.first_name if user else obj.sender

    def get_receiver_name(self, obj):
        if not obj.receiver:
            return "System"
        user = User.objects.filter(email=obj.receiver).first() or User.objects.filter(nis=obj.receiver).first()
        return user.first_name if user else obj.receiver

    def get_formatted_time(self, obj):
        if obj.timestamp:
            return timezone.localtime(obj.timestamp).strftime("%H:%M %p")
        return None
            
    def get_formatted_date(self, obj):
        if obj.timestamp:
            today = timezone.localdate()
            yesterday = today - timezone.timedelta(days=1)
            txn_date = timezone.localtime(obj.timestamp).date()
            if txn_date == today:
                return "Today"
            elif txn_date == yesterday:
                return "Yesterday"
            return txn_date.strftime("%d %b, %Y")
        return None


class PaymentRequestSerializer(serializers.Serializer):
    nis = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    amount = serializers.IntegerField(min_value=1, help_text="Amount to deduct")
    merchant_token = serializers.CharField(help_text="Token for the merchant stand")
    reference_id = serializers.CharField(
        max_length=255, 
        help_text="Unique transaction reference generated by frontend for idempotency"
    )


class StudentDashboardSerializer(serializers.Serializer):
    user = UserBalanceSerializer()
    shift_start = serializers.CharField()
    shift_end = serializers.CharField()
    supervisor_name = serializers.CharField()
    transactions = TransactionSerializer(many=True)