from rest_framework import serializers
from django.contrib.auth import get_user_model
from .models import Transaction, MerchantStand

User = get_user_model()

class UserBalanceSerializer(serializers.ModelSerializer):
    division_name = serializers.CharField(source='division.name', read_only=True)
    
    class Meta:
        model = User
        fields = ['email', 'nis', 'first_name', 'current_saldo', 'division_name', 'role']

class TransactionSerializer(serializers.ModelSerializer):
    merchant_stand_name = serializers.CharField(source='merchant_stand.name', read_only=True)

    class Meta:
        model = Transaction
        fields = ['id', 'amount', 'type', 'timestamp', 'description', 'sender', 'receiver', 'merchant_stand', 'merchant_stand_name', 'reference_id']

class PaymentRequestSerializer(serializers.Serializer):
    nis = serializers.CharField(help_text="User's NIS from the QR code")
    amount = serializers.IntegerField(min_value=0, help_text="Amount to deduct")
    merchant_token = serializers.CharField(help_text="Token for the merchant stand")
    reference_id = serializers.UUIDField(help_text="Unique transaction reference generated by frontend for idempotency")
