# Generated by Django 6.0.2 on 2026-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.AddField(
            model_name='user',
            name='division_name',
            field=models.CharField(blank=True, default='Food Service', max_length=100, null=True),
        ),
    ]
