# Generated by Django 6.0.2 on 2026-06-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_division_user_division_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='division_name',
            field=models.CharField(blank=True, default='UNREGISTERED', max_length=100, null=True),
        ),
    ]
