# Generated by Django 6.0.2 on 2026-08-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_buyer_remove_ticket_email_remove_ticket_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='ticketing.buyer'),
        ),
    ]