# Generated by Django 6.0.2 on 2026-07-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(help_text='Secret token assigned to the merchant terminal', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, help_text='Identifier (Email/NIS) of the sender. Null for system distributions.', max_length=255, null=True)),
                ('receiver', models.CharField(blank=True, help_text='Identifier (Email/NIS) of the receiver. Null for terminal checkout payments.', max_length=255, null=True)),
                ('reference_id', models.CharField(blank=True, help_text='Unique client token (idempotency key) to prevent double-deduction', max_length=255, null=True, unique=True)),
                ('amount', models.BigIntegerField()),
                ('type', models.CharField(choices=[('DISTRIBUTION', 'Distribution'), ('PAYMENT', 'Payment'), ('EXPIRATION', 'Expiration'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ccpay.merchantstand')),
            ],
        ),
    ]
