# Generated by Django 6.0.2 on 2026-08-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(help_text='Email of the committee member this schedule applies to', max_length=255, unique=True)),
                ('senin', models.BooleanField(default=False)),
                ('selasa', models.BooleanField(default=False)),
                ('rabu', models.BooleanField(default=False)),
                ('kamis', models.BooleanField(default=False)),
                ('jumat', models.BooleanField(default=False)),
                ('sabtu', models.BooleanField(default=False)),
                ('minggu', models.BooleanField(default=False)),
            ],
        ),
    ]
