# Generated by Django 6.0.2 on 2026-09-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccpay', '0002_weeklydutyschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklydutyschedule',
            old_name='jumat',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='weeklydutyschedule',
            old_name='kamis',
            new_name='h2',
        ),
        migrations.RenameField(
            model_name='weeklydutyschedule',
            old_name='minggu',
            new_name='h3',
        ),
        migrations.RenameField(
            model_name='weeklydutyschedule',
            old_name='rabu',
            new_name='h4',
        ),
        migrations.RenameField(
            model_name='weeklydutyschedule',
            old_name='sabtu',
            new_name='h5',
        ),
        migrations.RenameField(
            model_name='weeklydutyschedule',
            old_name='selasa',
            new_name='h6',
        ),
        migrations.RenameField(
            model_name='weeklydutyschedule',
            old_name='senin',
            new_name='h7',
        ),
        migrations.AddField(
            model_name='weeklydutyschedule',
            name='h8',
            field=models.BooleanField(default=False),
        ),
    ]
