# Generated by Django 6.0.2 on 2026-05-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccpay', '0002_merchantstand'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant_stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ccpay.merchantstand'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.UUIDField(blank=True, help_text='Unique reference for payment idempotency', null=True, unique=True),
        ),
    ]
