# Generated by Django 6.0.2 on 2026-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccpay', '0003_transaction_merchant_stand_transaction_reference_id'),
        ('user', '0004_remove_user_division_user_division_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shift',
            name='user',
        ),
        migrations.AlterField(
            model_name='merchantstand',
            name='token',
            field=models.CharField(help_text='Secret token assigned to the merchant terminal', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='Unique client token to prevent double-deduction', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
