# Generated by Django 6.0.2 on 2026-06-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccpay', '0005_alter_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.CharField(blank=True, help_text='Identifier (Email/NIS) of the receiver. Null for terminal checkout payments.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(blank=True, help_text='Identifier (Email/NIS) of the sender. Null for system distributions.', max_length=255, null=True),
        ),
    ]
